INPOBJS   =       input/cursor.o input/powerpad.o input/zapper.o input/arkanoid.o input/shadow.o input/fkb.o

input/cursor.o:		input/cursor.c
input/zapper.o:		input/zapper.c
input/powerpad.o:	input/powerpad.c
input/arkanoid.o:	input/arkanoid.c
input/shadow.o:		input/shadow.c
input/fkb.o:		input/fkb.c input/fkb.h
