MUOBJS   =	boards/simple.o boards/malee.o boards/supervision.o boards/novel.o boards/super24.o boards/h2288.o boards/sachen.o boards/8237.o

boards/simple.o:       boards/simple.c
boards/malee.o:		boards/malee.c
boards/supervision.o:	boards/supervision.c
boards/novel.o:		boards/novel.c
boards/super24.o:	boards/super24.c
boards/h2288.o:		boards/h2288.c
boards/sachen.o:	boards/sachen.c
